### ISSUE TITLE
Clean Code

### ISSUE THREAD

**Issue by chanwoolkim** [chanwool3000/ToPI#1]
I have been the only person working on the code so far, except in a few places. Since most of our estimates are very sensitive, we need to make sure that there are no (or at least minimal) errors in the code. I think the best way to do this is to do the following:

## Replicate Current Code
- [x] Run `master.do` and see if the code runs one-click
  * In theory, you should only have to change the first two lines (`code_path` and `master_math`). However, because most of the raw data files are not in the shared TOPI folder for data security reasons, you may have to start from `data_merge` part of Data Preparation section of the code.
  * Git is smart and automatically tracks `.png` and `.tex` files. If there are no changes to the graphics (i.e. we get the same results), then you will not have to push back the changes.

### Principles
This is the most important exercise. Here are some of the principles we want to follow:
- We want to make sure that we use data with same sample size in all our analyses.
- We want to make sure that when we use any scales, their direction is clearly defined 
  * For example, I know for HOME not only that 1 is Yes and 0 is No but also that 1 is Good and 0 is Bad).
- We want to make sure that when we sum over any items (or take the average), we are doing the job correctly.
  * Many of our variables have lots of missings. We figured before that when we sum instead of taking the averages, we do not weigh each question equally. We want to make sure that similar issues do not occur for other scales.
- We do not want to have any randomness inside the code
  * By randomness I mean our results should not change each time we run the code. I think there are two places where this might matter: when we impute covariates and when we bootsrtap. I set seed in the imputing part but bootsrtapping by nature should produce different (but not radically different) results each time. We should locate if there are any other randomness I missed.

### To-Do
- [ ] Check errors in code, and report to everyone if there is any
  - [ ] Check if we use the same sample in all analysis
  - [ ] Check if we use all instruments correctly
  - [ ] Check if we sum/take mean of items correctly
  - [ ] Check there is no randomness
- [ ] Check if the code matches the analysis/stories we address in the paper

### Code Organisation
- [ ] Look for places where we can use more abstraction 
  * One major improvement I made in the current version of the code is that I separated out the common parts of the code and placed them in `function` subdirectory. This includes what we call **pile charts** and preparing data feeding into them. I would love to have more abstraction since that will make our code a lot simpler.
- [ ] Reorganise code for better readability/speed
  * We might have some parts of the code that are unnecessary/redundant.

### Automation
- [ ] Remove unnecessary `//` at the end of the `.tex` tables produced
  * I am using Stata's `frmttable` function to output tables into `.tex` files. One terrible issue it causes is that for some reason the output `.tex` files always have an extra `//` at the end. I had to remove them manually before we source these tables in the main draft `.tex` file. It would be great to automate this (does not have to happen inside Stata).
- [ ] Check if we can use inequality signs (e.g. `<` as a row name in `frmttable`

### Graphics
- [ ] Try to see if we can increase text sizes for long questions
  * Maybe break the question into two lines?
- [ ] (Maybe) use R to produce "pile charts"
  * `ggplot2` and `geom_point` are the best. If it does not take too much effort, use them instead.
  * We can start [here](http://www.hargaden.com/enda/using-rs-ggplot2-with-stata/).
